# Generated by Django 5.0.3 on 2024-03-28 17:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('leaderboard', '0002_remove_leaderboard_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserReviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_review', models.TextField(max_length=100)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField(editable=False, unique=True)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='leaderboard.leaderboard')),
            ],
        ),
    ]
