# Generated by Django 5.0.3 on 2024-03-29 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userreviews',
            old_name='time',
            new_name='created',
        ),
    ]
