# Generated by Django 5.0.3 on 2024-03-29 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_remove_userreviews_username_userreviews_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userreviews',
            name='slug',
        ),
    ]
