# Generated by Django 5.0.3 on 2024-03-29 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_remove_userreviews_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='userreviews',
            name='slug',
            field=models.SlugField(default=1, editable=False, unique=True),
            preserve_default=False,
        ),
    ]
