# Generated by Django 5.0.3 on 2024-03-29 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0005_userreviews_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userreviews',
            name='slug',
        ),
    ]
