# Generated by Django 4.0.5 on 2024-03-13 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Leaderboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.TextField(max_length=20)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('game_type', models.TextField(max_length=20)),
                ('game_settings', models.TextField(max_length=20)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('final_score', models.IntegerField(max_length=10)),
            ],
        ),
    ]
