# Generated by Django 4.0.5 on 2024-03-14 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_remove_leaderboard_updated_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaderboard',
            name='slug',
            field=models.SlugField(editable=False, null=True, unique=True),
        ),
    ]
