# Generated by Django 4.0.5 on 2024-03-14 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_leaderboard_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaderboard',
            name='slug',
            field=models.SlugField(default='foo', editable=False, unique=True),
            preserve_default=False,
        ),
    ]
