# Generated by Django 5.0.3 on 2024-03-15 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0006_alter_category_options_alter_leaderboard_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leaderboard',
            name='game_settings',
        ),
    ]
