# Generated by Django 5.0.3 on 2024-03-17 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0007_remove_leaderboard_game_settings'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['category'], 'verbose_name_plural': 'Categories'},
        ),
    ]
