# Generated by Django 5.0.3 on 2024-03-19 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0009_leaderboard_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaderboard',
            name='final_score',
            field=models.IntegerField(max_length=10),
        ),
    ]
