# Generated by Django 5.0.3 on 2024-03-19 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0010_alter_leaderboard_final_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaderboard',
            name='final_score',
            field=models.IntegerField(),
        ),
    ]
