# Generated by Django 5.0.3 on 2024-03-24 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0011_alter_leaderboard_final_score'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Leaderboard',
        ),
    ]
